apiVersion: v1
appVersion: "12"
description: ASG Mobius provides an intelligent information management solution that
  delivers content services with a granular policy management foundation to digitally
  transform enterprise content and data according to corporate policies and regulatory
  compliance.
home: https://asg.com/
keywords:
- asg
- mobius
- server
- vdrnet
name: mobius
version: 12.0.0
